{
    "Version": "0.0.2",
    "EffectVersion": "0.0.1",
    "TemperatureAsShot": 5000.0,
    "TintAsShot": 9.56300000000000061107,
    "WBType": 8,
    "Visible": True,
    "LayerIndex": -1,
    "Temperature": 5000,
    "Tint": 9,
    "Exposure": 0,
    "Contrast": 0,
    "Brightness": 0,
    "Highlights": 0,
    "Shadows": 0,
    "Whites": 0,
    "Blacks": 0,
    "Clarity": 0,
    "Vibrance": 0,
    "Saturation": 0,
    "ProfileID": "TSColor",
    "CurveRGB": [
        0,
        0,
        255,
        255
    ],
    "CurveRed": [
        0,
        0,
        255,
        255
    ],
    "CurveGreen": [
        0,
        0,
        255,
        255
    ],
    "CurveBlue": [
        0,
        0,
        255,
        255
    ],
    "CurveLuma": [
        0,
        0,
        255,
        255
    ],
    "RGBToneMinThr": 25,
    "RGBToneMidThr": 50,
    "RGBToneMaxThr": 75,
    "RGBToneHighlights": 0,
    "RGBToneLights": 0,
    "RGBToneDarks": 0,
    "RGBToneShadows": 0,
    "HSLTunnerHueRed": 0,
    "HSLTunnerHueOrange": 0,
    "HSLTunnerHueYellow": 0,
    "HSLTunnerHueGreen": 0,
    "HSLTunnerHueAqua": 0,
    "HSLTunnerHueBlue": 0,
    "HSLTunnerHuePurple": 0,
    "HSLTunnerHueMagenta": 0,
    "HSLTunnerSaturationRed": 0,
    "HSLTunnerSaturationOrange": 0,
    "HSLTunnerSaturationYellow": 0,
    "HSLTunnerSaturationGreen": 0,
    "HSLTunnerSaturationAqua": 0,
    "HSLTunnerSaturationBlue": 0,
    "HSLTunnerSaturationPurple": 0,
    "HSLTunnerSaturationMagenta": 0,
    "HSLTunnerLuminanceRed": 0,
    "HSLTunnerLuminanceOrange": 0,
    "HSLTunnerLuminanceYellow": 0,
    "HSLTunnerLuminanceGreen": 0,
    "HSLTunnerLuminanceAqua": 0,
    "HSLTunnerLuminanceBlue": 0,
    "HSLTunnerLuminancePurple": 0,
    "HSLTunnerLuminanceMagenta": 0,
    "HSLTunnerLuminanceGrayRed": 0,
    "HSLTunnerLuminanceGrayOrange": 0,
    "HSLTunnerLuminanceGrayYellow": 0,
    "HSLTunnerLuminanceGrayGreen": 0,
    "HSLTunnerLuminanceGrayAqua": 0,
    "HSLTunnerLuminanceGrayBlue": 0,
    "HSLTunnerLuminanceGrayViolet": 0,
    "HSLTunnerLuminanceGrayMagenta": 0,
    "ColorGradingMidtonesHue": 0,
    "ColorGradingMidtonesSat": 0,
    "ColorGradingMidtonesLuma": 0,
    "ColorGradingShadowsHue": 0,
    "ColorGradingShadowsSat": 0,
    "ColorGradingShadowsLuma": 0,
    "ColorGradingHighlightsHue": 0,
    "ColorGradingHighlightsSat": 0,
    "ColorGradingHighlightsLuma": 0,
    "ColorGradingGlobalHue": 0,
    "ColorGradingGlobalSat": 0,
    "ColorGradingGlobalLuma": 0,
    "ColorGradingBlending": 50,
    "ColorGradingBalance": 0,
    "DetailBoostStrength": 10,
    "DetailBoostRadius": 100,
    "DetailBoostDetail": 25,
    "DenoiseLuma": 0,
    "DenoiseLumaDetail": 50,
    "DenoiseLumaConstrast": 0,
    "DenoiseChroma": 0,
    "DenoiseChromaDetail": 50,
    "DenoiseChromaSmooth": 50,
    "GrainOverallGrainStrength": 0,
    "GrainShadows": 30,
    "GrainMidtones": 50,
    "GrainHighlights": 15,
    "GrainSize": 30,
    "GrainRoughness": 50,
    "GrainColorVariation": 10,
    "GrainStyle": 0,
    "LensConfigSwitch": 0,
    "LensModel": 0,
    "LensConfigMode": 1,
    "LensConfigMakerName": "",
    "LensConfigLensName": "",
    "LensConfigDistortion": 100,
    "LensConfigVignetting": 100,
    "LensManualDistortion": 0,
    "LensManualVignetting": 0,
    "LensManualVignettingMidpoint": 50,
    "LensConstrainCrop": 1,
    "RedPrimaryHue": 0,
    "RedPrimarySaturation": 0,
    "GreenPrimaryHue": 0,
    "GreenPrimarySaturation": 0,
    "BluePrimaryHue": 0,
    "BluePrimarySaturation": 0
}